[build]
  command = "pip install -r requirements.txt"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.9"

[dev]
  framework = "#custom"
  command = "gunicorn --bind 0.0.0.0:8888 --reuse-port --reload main:app"
  targetPort = 8888
  port = 8888
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"